//
//  VehicleMeasurement.swift
//  PorscheConnect
//
//  Created by William Alexander on 07/01/2025.
//

enum VehicleMeasurement: String, CaseIterable {
    case acvState = "ACV_STATE"
    case alarmState = "ALARM_STATE"
    case batteryChargingState = "BATTERY_CHARGING_STATE"
    case batteryLevel = "BATTERY_LEVEL"
    case bleidDdaData = "BLEID_DDADATA"
    case chargingProfiles = "CHARGING_PROFILES"
    case chargingSettings = "CHARGING_SETTINGS"
    case chargingSummary = "CHARGING_SUMMARY"
    case climatizerState = "CLIMATIZER_STATE"
    case departures = "DEPARTURES"
    case eRange = "E_RANGE"
    case fuelLevel = "FUEL_LEVEL"
    case fuelReserve = "FUEL_RESERVE"
    case globalPrivacyMode = "GLOBAL_PRIVACY_MODE"
    case gpsLocation = "GPS_LOCATION"
    case heatingState = "HEATING_STATE"
    case hvacState = "HVAC_STATE"
    case intermediateServiceRange = "INTERMEDIATE_SERVICE_RANGE"
    case intermediateServiceTime = "INTERMEDIATE_SERVICE_TIME"
    case lockStateVehicle = "LOCK_STATE_VEHICLE"
    case mainServiceRange = "MAIN_SERVICE_RANGE"
    case mainServiceTime = "MAIN_SERVICE_TIME"
    case mileage = "MILEAGE"
    case oilLevelCurrent = "OIL_LEVEL_CURRENT"
    case oilLevelMax = "OIL_LEVEL_MAX"
    case oilLevelMinWarning = "OIL_LEVEL_MIN_WARNING"
    case oilServiceRange = "OIL_SERVICE_RANGE"
    case oilServiceTime = "OIL_SERVICE_TIME"
    case openStateChargeFlapLeft = "OPEN_STATE_CHARGE_FLAP_LEFT"
    case openStateChargeFlapRight = "OPEN_STATE_CHARGE_FLAP_RIGHT"
    case openStateDoorFrontLeft = "OPEN_STATE_DOOR_FRONT_LEFT"
    case openStateDoorFrontRight = "OPEN_STATE_DOOR_FRONT_RIGHT"
    case openStateDoorRearLeft = "OPEN_STATE_DOOR_REAR_LEFT"
    case openStateDoorRearRight = "OPEN_STATE_DOOR_REAR_RIGHT"
    case openStateLidFront = "OPEN_STATE_LID_FRONT"
    case openStateLidRear = "OPEN_STATE_LID_REAR"
    case openStateServiceFlap = "OPEN_STATE_SERVICE_FLAP"
    case openStateSpoiler = "OPEN_STATE_SPOILER"
    case openStateSunroof = "OPEN_STATE_SUNROOF"
    case openStateSunroofRear = "OPEN_STATE_SUNROOF_REAR"
    case openStateTop = "OPEN_STATE_TOP"
    case openStateWindowFrontLeft = "OPEN_STATE_WINDOW_FRONT_LEFT"
    case openStateWindowFrontRight = "OPEN_STATE_WINDOW_FRONT_RIGHT"
    case openStateWindowRearLeft = "OPEN_STATE_WINDOW_REAR_LEFT"
    case openStateWindowRearRight = "OPEN_STATE_WINDOW_REAR_RIGHT"
    case pairingCode = "PAIRING_CODE"
    case parkingBrake = "PARKING_BRAKE"
    case parkingLight = "PARKING_LIGHT"
    case predPreconLocationExceptions = "PRED_PRECON_LOCATION_EXCEPTIONS"
    case predPreconUserSettings = "PRED_PRECON_USER_SETTINGS"
    case range = "RANGE"
    case remoteAccessAuthorization = "REMOTE_ACCESS_AUTHORIZATION"
    case servicePredictions = "SERVICE_PREDICTIONS"
    case theftState = "THEFT_STATE"
    case timers = "TIMERS"
    case tirePressure = "TIRE_PRESSURE"
    case vtsModes = "VTS_MODES"
}
